In [3]:
import torch
import numpy as np
# Goal of this file: document common usages of torch/numpy/primary data & process data with pytorch

In [5]:
# converting from primary data type list to tensor
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [6]:
# converting from numpy to tensor
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>


In [8]:
# generating a list of five elements with placeholder one; parameter is the dimension of the matrix we want
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [ ]:
# generating a 2x2 matrix with placeholder 2
torch.ones(2, 2)

In [ ]:
# generating a 3x3x3 matrix with values randomly betwen 0-1
torch.rand(3, 3, 3)

In [17]:
# when we want to reference the shape of a tensor with placeholder 1
zero_tensor = torch.zeros(4, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)
print(zero_tensor, ones_like_zeros)

torch.Size([4, 3]) torch.Size([4, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [18]:
# tensor supports numpy indicing
# ex. 1st row
zero_tensor[0]

tensor([0., 0., 0.])

In [19]:
# first column of every row
ones_like_zeros[:, 0]

tensor([1., 1., 1., 1.])

In [20]:
# create a copy 
x = ones_like_zeros.detach()
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [21]:
#matrix multiplication
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(1.6990)

In [22]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[1.0269, 1.1278, 0.7323, 0.8697, 1.0907],
        [1.0148, 1.3434, 0.9375, 0.9597, 1.2775],
        [1.0568, 1.2838, 1.2930, 1.2635, 1.4574],
        [1.3520, 1.6907, 1.1224, 1.0968, 1.5552],
        [1.4723, 1.6113, 0.9777, 1.0941, 1.3255]])

In [ ]:
# Exercise: Data Preprocessing
import torch
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt